baseURL = ""
relativeURLs = true
uglyURLs = true
title = "tygutowski"

[author]
name = "tygutowski"
image = "image/nuntu.png"
headline = "software engineering student interested in game development"
links = [
   { twitter = "https://twitter.com/tygutowski" },
   { github = "https://github.com/tygutowski" }
]