baseURL = "https://tygutowski.com/"
relativeURLs = true
title = "tygutowski"

[author]
name = "tygutowski"
image = "image/nuntu.png"
bio = "software engineering interested in game development"
links = [
   { twitter = "https://twitter.com/tygutowski" },
   { github = "https://github.com/tygutowski" }
]