[[main]]
  name = "projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "classes"
  pageRef = "classes"
  weight = 10
  
[[main]]
  #identifier = "github"
  name = "github"
  url = "https://github.com/tygutowski/tygutowski"
  weight = 50

[[main]]
  #identifier = "twitter"
  name = "twitter"
  url = "https://twitter.com/tygutowski"
  weight = 60