[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/tygutowski/tygutowski"
  weight = 50

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/tygutowski"
  weight = 60