colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["projects"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "image/viridian-background.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/projects"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showAuthor = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background
  showDraftLabel = false
  showEdit = false
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = true
  sharingLinks = false

[list]
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
