colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["projects"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "hero" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/cover.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/projects"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showAuthor = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background
  showDraftLabel = false
  showEdit = false
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  sharingLinks = false

[list]
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
